name: build_runner_optimizer
description: A simple tool to optimize the build_runner running time.
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  glob: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
